// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNTI5knlfU9dBcfDlEhii08Z8V2yweReU',
    appId: '1:395147060699:web:48c58bd58e877ee13db3fe',
    messagingSenderId: '395147060699',
    projectId: 'shiba-app-f0248',
    authDomain: 'shiba-app-f0248.firebaseapp.com',
    storageBucket: 'shiba-app-f0248.firebasestorage.app',
    measurementId: 'G-PD2R6Z3Y6W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIT2t6duymxc7euH2FhbGUlEUdVR-sl5E',
    appId: '1:395147060699:android:7d24ca6b82de3d803db3fe',
    messagingSenderId: '395147060699',
    projectId: 'shiba-app-f0248',
    storageBucket: 'shiba-app-f0248.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrVvvEhjDtvqu3CWRRwd4ya7h5akUJuKQ',
    appId: '1:395147060699:ios:60f2297224ff398a3db3fe',
    messagingSenderId: '395147060699',
    projectId: 'shiba-app-f0248',
    storageBucket: 'shiba-app-f0248.firebasestorage.app',
    iosBundleId: 'com.example.itr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrVvvEhjDtvqu3CWRRwd4ya7h5akUJuKQ',
    appId: '1:395147060699:ios:60f2297224ff398a3db3fe',
    messagingSenderId: '395147060699',
    projectId: 'shiba-app-f0248',
    storageBucket: 'shiba-app-f0248.firebasestorage.app',
    iosBundleId: 'com.example.itr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNTI5knlfU9dBcfDlEhii08Z8V2yweReU',
    appId: '1:395147060699:web:0a3c3ec47bae27173db3fe',
    messagingSenderId: '395147060699',
    projectId: 'shiba-app-f0248',
    authDomain: 'shiba-app-f0248.firebaseapp.com',
    storageBucket: 'shiba-app-f0248.firebasestorage.app',
    measurementId: 'G-QW5S6WJGD0',
  );
    <!-- Google Sign-in URL Scheme -->
	<key>CFBundleURLTypes</key>
	<array>
		<dict>
			<key>CFBundleTypeRole</key>
			<string>Editor</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>com.googleusercontent.apps.123456789-abcdefg</string>
			</array>
		</dict>
	</array>
}
